name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake animation and push to the output branch
        uses: Platane/snk@v3
        with:
          github_user_name: DevWesCode
          outputs: |
            dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
